### ISSUE TITLE
Upgrade to svelte 4

### ISSUE THREAD

**Issue by devcsrj** [ankurrsinghal/svelte-legos#100]
When installing, `npm` will complain with:

```
npm ERR! Found: svelte@4.1.2
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^4.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^3.54.0" from svelte-legos@0.2.1
npm ERR! node_modules/svelte-legos
npm ERR!   dev svelte-legos@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

```

**Comment by LeoCaprile** [comment]
@ankurrsinghal Hey I came back, was looking trough the docs and seen this guide:
https://svelte.dev/docs/v4-migration-guide
I would make a try to migrate the library, and if I success, I'll open the MR.

**Comment by LeoCaprile** [comment]
I checked, it is already updated.

**Comment by devcsrj** [comment]
Looks like its been addressed by https://github.com/ankurrsinghal/svelte-legos/pull/91/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R74
