### ISSUE TITLE
Confetti run

### ISSUE THREAD

**Issue by tinkerbaj** [ankurrsinghal/svelte-legos#101]
How can I run confetti programmatically instead of using a button or something?

**Comment by LeoCaprile** [comment]
Please see [canvas-confetti](https://www.npmjs.com/package/canvas-confetti) repository to use it detached from svelte legos actions.

**Comment by bobbymannino** [comment]
Can this be closed? @tinkerbaj @LeoCaprile @ankurrsinghal

**Comment by tinkerbaj** [comment]
Yes, it can :) Thanks for help

**Comment by tinkerbaj** [comment]
I make it
