### ISSUE TITLE
New release of recent updates

### ISSUE THREAD

**Issue by bourhaouta** [ankurrsinghal/svelte-legos#105]
I can see that a lot of great work got merged, especially the upgrade of Svelte which I need to upgrade a project to Svelte 4
Is there a planned release soon?

Thank you!

**Comment by RonB** [comment]
Yes, please release this to npm.org. Using the master as dependency results in errors.

**Comment by ankurrsinghal** [comment]
Sorry guys was out for some days, I will see and publish a new version. Thank you so much for the push.

**Comment by ankurrsinghal** [comment]
Published a new 0.2.2 version.

**Comment by bourhaouta** [comment]
thank you so much 🙌
