### ISSUE TITLE
bug: usage of actions in docs

### ISSUE THREAD

**Issue by paoloricciuti** [ankurrsinghal/svelte-legos#11]
Most of the examples in the docs make it seems like you can use the actions on Components...this is simply not permitted in svelte. This can lead inexperienced devs to wonder how they can make their custom button component draggable. I understand it is for simplicity but a bit of markup never killed anyone....I'd say the correct thing to do is update the examples.

**Comment by ankurrsinghal** [comment]
You mean how Svelte actions are only permitted on the native DOM Elements?

**Comment by paoloricciuti** [comment]
Exactly

**Comment by ankurrsinghal** [comment]
@paoloricciuti Thanks for raising the issue, made the changes!
