### ISSUE TITLE
`cssVarStore` is not a Writable

### ISSUE THREAD

**Issue by julien-blanchon** [ankurrsinghal/svelte-legos#117]
I would like to use `cssVarStore` store with `storage` one but `cssVarStore` don't return update so it's not a Writable and storage is complaining about it

**Comment by julien-blanchon** [comment]
`Property 'update' is missing in type '{ subscribe: (this: void, run: Subscriber<string>, invalidate?: Invalidator<string> | undefined) => Unsubscriber; set: (value: string) => void; }' but required in type 'Writable<string>`

**Comment by julien-blanchon** [comment]
https://github.com/ankurrsinghal/svelte-legos/pull/118

**Comment by julien-blanchon** [comment]
Currently this is my only workaround:
```ts
let bg_css = cssVarStore('--bg');
let bg = storage({ ...bg_css, update: (updater) => bg_css.set(updater($bg_css)) }, 'bg');
```

**Comment by ankurrsinghal** [comment]
Thanks @julien-blanchon for the heads up. Merged the PR.
