### ISSUE TITLE
feat: areYouSure action

### ISSUE THREAD

**Issue by bobbymannino** [ankurrsinghal/svelte-legos#128]
This action is basically a tool that opens a confirm action modal to the user, from they're the user can accept - which will run a function passed into it - or close the modal and do nothing. It would work something like this;

```svelte
<button 
    onclick={() => areYouSure(() => deleteRecord(record.id), { title:"Are you sure you want to delete the record?" })}
>Delete</button>
```

**Comment by jalavosus** [comment]
@bobbymannino I've implemented this in [my fork of svelte-legos](https://github.com/jalavosus/svelte-legos), with an example being found on the [docs site](https://sveltelegos-blue.vercel.app/guides/actions/confirmAction/). Let me know if this is what you're looking for.

**Comment by bobbymannino** [comment]
@jalavosus thats exactly what im after, thank you, i know its in a fork but im still going to close this issue here, saw your repo is also made for svelte 5 which is cool, nice work
