### ISSUE TITLE
bug: app reloads completely when clicking on a link, it should be hydrate to SPA mode.

### ISSUE THREAD

**Issue by ankurrsinghal** [ankurrsinghal/svelte-legos#33]

**Comment by symsmith** [comment]
@ankurrsinghal Removing `e.stopPropagation()` in guides/+layout.svelte seems to fix this, is it there for a reason? Mobile menu still works fine without it

**Comment by ankurrsinghal** [comment]
I added it for a reason, I will check that, but we need to sort this out, it's bugging lot of developers.

**Comment by ankurrsinghal** [comment]
Deploy the docs and page are not reloading, thanks for fixing this, @symsmith.
