### ISSUE TITLE
Bug: Module '"svelte-legos"' has no exported member 'confettiAction'.

### ISSUE THREAD

**Issue by LeoCaprile** [ankurrsinghal/svelte-legos#39]
Can't import confettiAction like the docs says
![imagen](https://user-images.githubusercontent.com/71847541/226075969-af879ccd-12bb-436b-9030-2977b779821c.png)

Getting the followed error
![imagen](https://user-images.githubusercontent.com/71847541/226075878-38761ff7-a6b7-45fd-a621-7ce98e0a3025.png)

**Comment by ankurrsinghal** [comment]
Republished the package to v0.0.6 with latest build, can you try again please?

**Comment by ankurrsinghal** [comment]
Seems like you are building a Game in Svelte, 😃. That's nice!

**Comment by LeoCaprile** [comment]
Is imported nice now! 
![imagen](https://user-images.githubusercontent.com/71847541/226076905-7dad9c13-7cba-401b-8a15-d07648013548.png)
Looking forward to contribute to this package!

**Comment by LeoCaprile** [comment]
> @LeoCaprile Seems like you are building a Game in Svelte, smiley. That's nice! I got the idea for a confettiAction only after I was myself building a Solitaire Game in Svelte.

Really nice! I'm building a sort of sverdle to learn svelte!
