### ISSUE TITLE
bug: `intervalFnStore` demo crashes with an empty input

### ISSUE THREAD

**Issue by symsmith** [ankurrsinghal/svelte-legos#42]
Getting `Uncaught Error: Interval is not a safe integer` on the [`intervalFnStore` demo page](https://svelte-legos.singhalankur.com/guides/stores/intervalFnStore/) when the input is cleared, then after pausing I can’t resume again.

**Comment by ankurrsinghal** [comment]
Hi @symsmith wow, thanks for finding this out, let's fix this, please contribute in any capacity you like.
