### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by Crisfole** [ankurrsinghal/svelte-legos#84]
Geolocation is very easy to implement as a store. Again: one of those browser APIs that was _meant_ to be a store.

https://github.com/parkingboss/svelte-utils/blob/master/src/geo.ts

That code can be easily adapted.

**Comment by Crisfole** [comment]
I'm not using svelte-legos at the moment, but it looks great. Just wanted to point you at an implementation you can crib off of! Hope it helps!

**Comment by bobbymannino** [comment]
Would @ankurrsinghal like me to add this?
