### ISSUE TITLE
messageStore shows message behind html <dialog> element

### ISSUE THREAD

**Issue by levinhtin** [ankurrsinghal/svelte-legos#90]
When the html Dialog is opening, and call method messageStore("test", "success")
The message is displayed behind

<img width="208" alt="Screenshot 2023-06-12 at 11 36 00" src="https://github.com/ankurrsinghal/svelte-legos/assets/11834124/67e4bd06-8d20-4d44-a3cb-24338f7c4dbe">

**Comment by ankurrsinghal** [comment]
Thanks for reporting this @levinhtin, let me check this out. 🙂

**Comment by LeoCaprile** [comment]
looks like a z-index problem, maybe the dialog has a very high z-index? can you change it? @levinhtin

**Comment by levinhtin** [comment]
Yes, we can not set z-index with <dialog>

**Comment by LeoCaprile** [comment]
> Yes, we can not set z-index with

I think you can use z-index but the messageStore element has a `z-index: 9999`, if the dialog is below that number I think could work ok.
